# This file is used by the training script in train.ipynb. You can read more about
# the format and see more examples at https://github.com/OpenAccess-AI-Collective/axolotl.
# One of the parameters you might want to play around with is `num_epochs`: if you have a
# smaller dataset size, making that large can have good results.

base_model: meta-llama/Llama-2-7b-chat-hf
base_model_config: meta-llama/Llama-2-7b-chat-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: /content/drive/MyDrive/ML/data/1984_train.jsonl
    type: alpaca_instruct.load_no_prompt
val_set_size: 0.05
output_dir: /content/drive/MyDrive/ML/data/style_transfer/models/run_not_packed_4eps

sequence_len: 512
sample_packing: false

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

gradient_accumulation_steps: 8
micro_batch_size: 32
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 15
save_steps: 10
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
